name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OWNER: maruqes
    outputs:
      gateway_image: ${{ steps.set-images.outputs.gateway_image }}
      shortener_image: ${{ steps.set-images.outputs.shortener_image }}

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - id: build-gateway
        name: Construir e enviar imagem do gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./services/gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/gateway:latest
            ghcr.io/${{ env.OWNER }}/gateway:${{ github.sha }}

      - id: build-shortener
        name: Construir e enviar imagem do shortener
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./services/shortener/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/shortener:latest
            ghcr.io/${{ env.OWNER }}/shortener:${{ github.sha }}

      - id: set-images
        name: Definir outputs das imagens
        run: |
          echo "gateway_image=ghcr.io/${{ env.OWNER }}/gateway:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "shortener_image=ghcr.io/${{ env.OWNER }}/shortener:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Carregar chave SSH no agente
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # se usares passphrase na chave, descomenta a linha abaixo
          # ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Configurar SSH com ProxyCommand e ignorar host key
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/config
          Host target-server
            HostName sftp
            User sftp
            ProxyCommand openssl s_client -connect maruqes.com:10512 -servername sftp.maruqes.com -quiet
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
          EOF
          chmod 600 ~/.ssh/config

      - name: Fazer deploy no servidor
        run: |
          ssh target-server "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker pull ${{ needs.build.outputs.gateway_image }}"
          ssh target-server "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S docker pull ${{ needs.build.outputs.shortener_image }}"
          ssh target-server "echo '${{ secrets.SUDO_PASSWORD }}' | sudo -S k3s kubectl apply -f /home/sftp/workspace/k8s/"
