name: CI/CD Docker + Deploy k3s

on:
  push:
    branches:
      - main
    paths:
      - 'services/gateway/**'
      - 'services/shortener/**'
      - 'k8s/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      gateway-tag: ${{ steps.gateway.outputs.image }}
      shortener-tag: ${{ steps.shortener.outputs.image }}

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Configurar QEMU (multi-arch)
        uses: docker/setup-qemu-action@v2

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push do gateway
        id: gateway
        uses: docker/build-push-action@v4
        with:
          context: ./services/gateway
          file: ./services/gateway/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gateway:latest
            ghcr.io/${{ github.repository_owner }}/gateway:${{ github.sha }}
        # fornece a imagem final para o job de deploy
        outputs:
          image: ghcr.io/${{ github.repository_owner }}/gateway:${{ github.sha }}

      - name: Build & push do shortener
        id: shortener
        uses: docker/build-push-action@v4
        with:
          context: ./services/shortener
          file: ./services/shortener/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/shortener:latest
            ghcr.io/${{ github.repository_owner }}/shortener:${{ github.sha }}
        outputs:
          image: ghcr.io/${{ github.repository_owner }}/shortener:${{ github.sha }}

  deploy-to-k3s:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no home server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOME_SERVER_HOST }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          port: ${{ secrets.HOME_SERVER_PORT }}       # opcional, default 22
          script: |
            cd /caminho/para/o/projeto
            git pull origin main
            # Opcional: atualizar imagens nos YAMLs (se tiveres tags dinâmicas)
            # sed -i "s|gateway:.*|gateway:${{ needs.build-and-push.outputs.gateway-tag }}|g" k8s/gateway-service.yaml
            # sed -i "s|shortener:.*|shortener:${{ needs.build-and-push.outputs.shortener-tag }}|g" k8s/shortener-service.yaml
            kubectl apply -f k8s/
