name: Deploy to k3s

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    # Build Gateway
    - name: Build and Push Gateway
      run: |
        OWNER="${GITHUB_REPOSITORY_OWNER,,}"     # owner em lowercase
        TAG="${GITHUB_SHA,,}"                    # SHA em lowercase
        IMAGE="ghcr.io/${OWNER}/url-gateway:${TAG}"
        docker build -t "$IMAGE" ./services/gateway
        docker push "$IMAGE"
    
    # Build Shortener
    - name: Build and Push Shortener
      run: |
        OWNER="${GITHUB_REPOSITORY_OWNER,,}"     # owner em lowercase
        TAG="${GITHUB_SHA,,}"                    # SHA em lowercase
        IMAGE="ghcr.io/${OWNER}/url-shortener:${TAG}"
        docker build -t "$IMAGE" ./services/shortener
        docker push "$IMAGE"


  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup k3s connection
      uses: kodermax/kubectl-actions@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy Redis
      run: kubectl apply -f k8s/redis-statefulset.yaml

    - name: Deploy Shortener
      run: |
        # Usar o mesmo SHA em minúsculas
        LOWERCASE_SHA=$(echo "${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
        kubectl set image deployment/shortener \
          shortener=ghcr.io/${{ github.repository_owner }}/url-shortener:$LOWERCASE_SHA \
          --record

    - name: Deploy Gateway
      run: |
        # Usar o mesmo SHA em minúsculas
        LOWERCASE_SHA=$(echo "${{ github.sha }}" | tr '[:upper:]' '[:lower:]')
        kubectl set image deployment/gateway \
          gateway=ghcr.io/${{ github.repository_owner }}/url-gateway:$LOWERCASE_SHA \
          --record
