name: Deploy to k3s

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    # Build Gateway (context = root, Dockerfile apontado)
    - name: Build and Push Gateway
      run: |
        # GITHUB_REPOSITORY_OWNER e GITHUB_SHA já vêm como env vars
        OWNER="${GITHUB_REPOSITORY_OWNER,,}"   # shell faz lowercase
        TAG="${GITHUB_SHA,,}"
        IMAGE="ghcr.io/${OWNER}/url-gateway:${TAG}"
    
        docker build \
          -f services/gateway/Dockerfile \
          -t "$IMAGE" \
          .
    
        docker push "$IMAGE"


    
    # Build Shortener (idem)
    - name: Build and Push Shortener
      run: |
        OWNER="${GITHUB_REPOSITORY_OWNER,,}"
        TAG="${GITHUB_SHA,,}"
        IMAGE="ghcr.io/${OWNER}/url-shortener:${TAG}"
        docker build \
          -f services/shortener/Dockerfile \
          -t "$IMAGE" .
        docker push "$IMAGE"
  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - uses: actions/checkout@v4

    # instala o kubectl
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    # põe o kubeconfig no lugar certo
    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Deploy Redis
      run: kubectl apply -f k8s/redis-statefulset.yaml

    - name: Deploy Shortener
      run: |
        OWNER="${{ github.repository_owner,, }}"
        TAG="${{ github.sha,, }}"
        kubectl set image deployment/shortener \
          shortener=ghcr.io/${OWNER}/url-shortener:${TAG} --record

    - name: Deploy Gateway
      run: |
        OWNER="${GITHUB_REPOSITORY_OWNER,,}"
        TAG="${GITHUB_SHA,,}"
        kubectl set image deployment/gateway \
          gateway=ghcr.io/${OWNER}/url-gateway:${TAG} --record

